#! /usr/bin/env python

no_outline_pdfs_COI = {
    'a0100.1_academicaffairsreaccreditation': (
        ('Contents of Inventory', (2, 2)),
        ('Summary', (3, 3)),
        ('Historical Note', (4, 4)),
        ('Scope and Content Note', (5, 5)),
        ('List of sub-groups, series, and subseries', (6, 6)),
        ('Series descriptions', (7, 7)),
        ('Index terms', (11, 11)),
        ('Container List', (14, 14)),
        ('Appendix A', (52, 52)),
        ('Appendix B', (77, 77)),
        ),
    'a0100.academicaffairs': (
        ('Contents of Inventory', (1, 1)),
        ('Summary', (2, 2)),
        ('Biographica/Historical Note', (3, 3)),
        ('Scope and Content Note', (3, 3)),
        ('List of sub-groups, series, and subseries', (3, 3)),
        ('Series descriptions', (4, 4)),
        ('Index terms', (5, 5)),
        ('Container List', (8, 8)),
        ),
    'a0011_administrativeinformationsystemsrecords': (
        ('Contents of Inventory', (1, 1)),
        ('Summary', (2, 2)),
        ('Historical Note', (3, 3)),
        ('Scope and Content Note', (3, 3)),
        ('Index terms', (3, 3)),
        ('Container List', (4, 4)),
        ),
    'a0050_athleticdepartmentrecords': (
        ('Contents of Inventory', (1, 1)),
        ('Summary', (2, 2)),
        ('Historical Note', (3, 3)),
        ('Scope and Content Note', (3, 3)),
        ('Index terms', (4, 4)),
        ('Container List', (5, 5)),
        ),
    'a0001.1_fallfestrecords': (
        ('Contents of Inventory', (1, 1)),
        ('Summary', (2, 2)),
        ('Historical Note', (3, 3)),
        ('Scope and Content Note', (3, 3)),
        ('Index terms', (3, 3)),
        ('Container List', (4, 4)),
        ),
    'a0001_officeofchancellor': (
        ('Summary', (3, 3)),
        ('Historical Note', (4, 4)),
        ('Scope and Content Note', (5, 5)),
        ('List of sub-groups, series, and subseries', (6, 6)),
        ('Series descriptions', (8, 8)),
        ('Index terms', (26, 26)),
        ('Container List', (34, 34)),
        ),
    'a0004.2_commissiononthestatusofwomenrecords': (
        ('Contents of Inventory', (2, 2)),
        ('Summary', (3, 3)),
        ('Biographica/Historical Note', (4, 4)),
        ('Scope and Content Note', (5, 5)),
        ('List of sub-groups, series, and subseries', (5, 5)),
        ('Series descriptions', (6, 6)),
        ('Index terms', (8, 8)),
        ('Container List', (10, 10)),
        ),
    'a0302_deanofstudentsoffice': (
        ('Contents of Inventory', (1, 1)),
        ('Summary', (2, 2)),
        ('Historical Note', (3, 3)),
        ('Scope and Content Note', (3, 3)),
        ('List of sub-groups, series, and subseries', (4, 4)),
        ('Series descriptions', (4, 4)),
        ('Index terms', (5, 5)),
        ('Container List', (7, 7)),
        ),
    'a0301_facultyclubrecords': (
        ('Contents of Inventory', (1, 1)),
        ('Summary', (2, 2)),
        ('Historical Note', (3, 3)),
        ('Scope and Content Note', (3, 3)),
        ('Index terms', (4, 4)),
        ('Container List', (5, 5)),
        ),
    'a0504_humanecologyrecords': (
        ('Contents of Inventory', (2, 2)),
        ('Summary', (3, 3)),
        ('Biographical/Historical Note', (4, 4)),
        ('Scope and Content Note', (4, 4)),
        ('List of sub-groups, series, and subseries', (5, 5)),
        ('Series descriptions', (5, 5)),
        ('Index terms', (6, 6)),
        ('Container List', (7, 7)),
        ),
    'a0407.1_instituteforenvironmentalstudies_saltdome': (
        ('Contents of Inventory', (2, 2)),
        ('Summary', (3, 3)),
        ('Biographical/Historical Note', (4, 4)),
        ('Scope and Content Note', (4, 4)),
        ('List of sub-groups, series, and subseries', (5, 5)),
        ('Series descriptions', (5, 5)),
        ('Index terms', (6, 6)),
        ('Container List', (7, 7)),
        ),
    'a0306_internationalstudentoffice': (
        ('Contents of Inventory', (1, 1)),
        ('Summary', (2, 2)),
        ('Historical Note', (3, 3)),
        ('Scope and Content Note', (3, 3)),
        ('List of sub-groups, series, and subseries', (3, 3)),
        ('Series descriptions', (4, 4)),
        ('Index terms', (5, 5)),
        ('Container List', (6, 6)),
        ),
    'a3000_cooperative_extension': (
        ('Contents of Inventory', (2, 2)),
        ('Summary', (3, 3)),
        ('Historical Note', (4, 4)),
        ('Scope and Content Note', (5, 5)),
        ('List of sub-groups, series, and subseries', (6, 6)),
        ('Series descriptions', (7, 7)),
        ('Index terms', (15, 15)),
        ('Container List', (17, 17)),
        ('Appendix A', (104, 104)),
        ('Appendix B', (112, 112)),
        ),
    'a5000_lsuphotocollection': (
        ('Contents of Inventory', (2, 2)),
        ('Summary', (3, 3)),
        ('Historical Note', (4, 4)),
        ('Scope and Content Note', (4, 4)),
        ('List of sub-groups, series, and subseries', (5, 5)),
        ('Series descriptions', (6, 6)),
        ('Index terms', (9, 9)),
        ('Container List', (11, 11)),
        ),
    'a0303_lsustudentunion': (
        ('Contents of Inventory', (1, 1)),
        ('Summary', (2, 2)),
        ('Historical Note', (3, 3)),
        ('Scope and Content Note', (3, 3)),
        ('List of sub-groups, series, and subseries', (4, 4)),
        ('Series descriptions', (4, 4)),
        ('Index terms', (5, 5)),
        ('Container List', (6, 6)),
        ),
    'a0004': (
        ('Summary', (2, 2)),
        ('Historical Note', (2, 2)),
        ('Scope and Content Note', (3, 3)),
        ('Index terms', (9, 9)),
        ('Container List', (12, 12)),
        ),
    'a0002_lsusystem': (
        ('Contents of Inventory', (2, 2)),
        ('Summary', (3, 3)),
        ('Biographical/Historical Note', (4, 4)),
        ('Scope and Content Note', (4, 4)),
        ('List of series', (4, 4)),
        ('Series descriptions', (5, 5)),
        ('Index terms', (6, 6)),
        ('Container List', (9, 9)),
        ),
}
